language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: P0zPKZCanXiEG0vIquB9k0kISGlixod3NTNhtO2oTIsUQMedJaqyUpAU6uAaobadTtyVxVTYqAiBw4mzU+aiQtcHLq9Vd3MyYvKDaRuNOEoYBo+Wds6SE8oDjWIs5v1x7hvYrBlc8oP22USpPDeX56AcfUMPT+Z8WEcw9KboBEwmjliMKoINFGTuXHz7Wc3Ly1O3/8Y4nQ39e1iIXJTxmwglUfoz2iBnxJuPRI7zQb/MR6VgXlMKwGPkLQ9brekOD5Pmz/aAKiDYujOsxjahmtkiyJSBb8Nu2MYFRG26HMEoiK6gGlqRWY5d1d5O0j/JAZ73ePA4XFdXi9lbI1YjE3RZZkopfdSWXzV331KoHRIN+MDTrDVw9gdyrryZ+EkEbb0WMd64KtYNKNtmftS1g+q0B66yFHIVgicMQX4mgvNQkP7pgyHNBf4/DhUB9q3q4FMPW7NO7+KMAQQJjU9hPme0+P4nsslTunzlQh1SEScCTtgJGMgJune9t73aeXZQAJ3ONq4oF3QV8W4aFGnVc6UGxtoeEW6DMv54Albl2UppQe0TjqjPULkNecU+wRvDNvAmwRdhGNbIvRcArdYdgwLBcLHWbgjwoDVSRagu8rS9Wqt6ax1zbovAxlZNNfcAlwM7jhMv3UeBwcGVaz5cjs6wUXk4s1FHpG7q1cPzqrA=
  app: test000000
